base_url = "https://LexKicks.gitlab.io"
title = "LexKicks"
description = "This is an example description"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content"

menu = [
    { name = "/posts", url = "/posts", weight = 1 }
]

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/lakshita-shetty/", icon = "linkedin" },
    { name = "github", url = "https://github.com/Lak-shi", icon = "github" },
    { name = "slack", url = "https://lak-shi.github.io/", icon = "slack" },
]

custom_css = []

